
import './globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={null}>
        {/* <Web3Provider > */}
          {children}
        {/* </Web3Provider> */}
      </body>
    </html>
  )
}
