import { Web3Provider } from '../../context/Web3Context'
import './globals.css'
import Navbar from '../../components/Navbar'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={null}>
        <Web3Provider >
          <Navbar />
          {children}
        </Web3Provider>
      </body>
    </html>
  )
}
